# Generated by Django 3.2.8 on 2021-12-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InforUser',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('time', models.DateTimeField(default=None, null=True)),
                ('money', models.FloatField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('note', models.TextField(max_length=300, null=True)),
            ],
        ),
    ]
