# Generated by Django 3.2.8 on 2021-12-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inforuser',
            old_name='money',
            new_name='monney',
        ),
        migrations.AlterField(
            model_name='inforuser',
            name='note',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='inforuser',
            name='time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
