# Generated by Django 3.2.8 on 2022-01-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noti', '0002_noti_approve'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotiUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('approve', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='noti',
            name='approve',
        ),
    ]
