# Generated by Django 3.2.8 on 2022-01-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noti', '0003_auto_20220117_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='notiuser',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
